import React from "react";
import { Button } from "./button";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/LWnQnI8BhggiTGgPMIXdw6/JS-SQUAD?node-id=1-25&t=Lw4rKVlyF0Ey7uRB-4",
  {
    props: {
      type: figma.enum("type", {
        "primary button": "primary-button",
        destructive: "destructive",
        subtle: "subtle",
        ghost: "ghost",
        "with icon": "with-icon",
        loading: "loading",
        outline: "outline",
        default: "default",
        link: "link",
        "just icon": "just-icon",
        "just icon circle": "just-icon-circle",
      }),
      state: figma.enum("state", {
        Default: "default",
        hover: "hover",
      }),
    },
    example: (props) => <Button />,
  }
);
